[package]
name = "lox-rs"
version = "0.0.0"
authors = ["Sebastian <sbooster884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug_trace_execution = []
debug_print_code = []

[dependencies]